### ISSUE TITLE
SilverStripe 4 support?

### ISSUE THREAD

**Issue by MightyMerio** [kinglozzer/silverstripe-mailgunner#14]
Are there any plans to update for ss4 ?  Or is there another library I ought to be looking at?

**Comment by lozcalver** [comment]
This module isn’t needed for SS4, as SS4 uses SwiftMailer so can be configured with any SwiftMailer plugin. For Mailgun you’ll probably want https://bitbucket.org/salevan/swiftmailer-mailgun-smtp-transport/src/master/. There are instructions for the configuration you’ll need here: https://docs.silverstripe.org/en/4/developer_guides/email/#configuration

It’ll probably be something like

```yml
---
Name: myemailconfig
After:
  - '#emailconfig'
---
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: salevan\mailgun\SmtpTransport
    calls:
      Domain: [ setMailgunDomain, ['<Domain Name>'] ]
      ApiKey: [ setPrivateApiKey, ['<Api Key>'] ]
```
