### ISSUE TITLE
Update use of deprecated Mailgun APIs

### ISSUE THREAD

**Issue by kinglozzer** [kinglozzer/silverstripe-mailgunner#9]
- Remove [`setApiVersion()`](https://github.com/kinglozzer/silverstripe-mailgunner/blob/4b3b70f07db54ae4fb0248fdbda346cfc5e0e646/src/Mailer.php#L60) and [`setSslEnabled()`](https://github.com/kinglozzer/silverstripe-mailgunner/blob/4b3b70f07db54ae4fb0248fdbda346cfc5e0e646/src/Mailer.php#L61)
- Replace [`BatchMessage()`](https://github.com/kinglozzer/silverstripe-mailgunner/blob/4b3b70f07db54ae4fb0248fdbda346cfc5e0e646/src/Mailer.php#L114) with `new Mailgun\Messages\BatchMessage`
- Replace [`MessageBuilder()`](https://github.com/kinglozzer/silverstripe-mailgunner/blob/4b3b70f07db54ae4fb0248fdbda346cfc5e0e646/src/Mailer.php#L117) with `new Mailgun\Messages\MessageBuilder`
- Replace [`sendMessage()`](https://github.com/kinglozzer/silverstripe-mailgunner/blob/4b3b70f07db54ae4fb0248fdbda346cfc5e0e646/src/Mailer.php#L126) with `message()`

**Comment by ARNHOE** [comment]
Any idea when this will be available?

**Comment by kinglozzer** [comment]
@ARNHOE When what will be available? Version `3.0.0` of this module uses `mailgun-php: 2.x`, the deprecated APIs don’t need to be updated for it to work 😃

**Comment by ARNHOE** [comment]
@kinglozzer Couldnt get dev-master work, but 2.x works perfectly. Found out after the comment

**Comment by rmsj** [comment]
Does this work for local development:

`Debug (line 140 of Mailer.php): Mailgun error: An HTTP Error has occurred! Check your network connection and try again.`

**Comment by kinglozzer** [comment]
It does work locally, can you check which version of this module you’re using and paste your mailgun config?

**Comment by rmsj** [comment]
Version installed is the latest I think.
The configuration is as per this

# Mailgun
---
After: 'silverstripe-mailgun'
---
Kinglozzer\SilverStripeMailgunner\Mailer:
  api_domain: 'some_long_sand_box_url_.mailgun.org'
  api_key: 'key-my-api-key'
---
After: 'silverstripe-mailgun'
Only:
  environment: 'dev'
---
# Get your own Postbin ID by visiting http://bin.mailgun.net
Kinglozzer\SilverStripeMailgunner\Mailer:
  api_endpoint: 'http://bin.mailgun.net/C6f04a3a'
  debug: true

**Comment by kinglozzer** [comment]
`composer show` will show you which version you have installed. That all looks correct, it’s very similar to the configuration I used for when working on the module. I simply skipped the environment conditions:

```yml
---
Name: mailgun
After: 'silverstripe-mailgun'
---
Kinglozzer\SilverStripeMailgunner\Mailer:
  api_domain: 'https://api.mailgun.net/v3/sandbox123456789987654321.mailgun.org'
  api_endpoint: 'http://bin.mailgun.net/12345abcde'
  api_key: 'key-1234564789876543212345678987654321'
  debug: true
```
